// All site copy lives here. English is the anchor language.
// Croatian copy to be finalized by Vedra — current HR strings are placeholders
// except where authentic Croatian source was recovered from the existing site.

export type Lang = 'en' | 'hr'

export type Illustration = 'leaf' | 'ripple' | 'wave' | 'grid' | 'curve' | 'botanical' | 'sunrise' | 'horizon' | 'none'
export type PlaceholderTheme = 'moss-ochre' | 'moss' | 'ochre' | 'neutral'

export const strings = {
  en: {
    meta: {
      wordmark: 'Trillian HR',
      location: 'Zagreb',
      practitioner: 'Vedra Regul Erent-Ondrušek',
    },
    nav: {
      approach: 'Approach',
      services: 'Services',
      story: 'Story',
      principles: 'Principles',
      contact: 'Contact',
      apply: 'Write',
    },
    hero: {
      eyebrow: '01 / Hello',
      line1: "I'm not a typical coach.",
      line2Prefix: 'Probably',
      line2Suffix: '.',
      rotating: ['worse', 'harder', 'weirder', 'stranger'],
      sub: "HR methodology meets somatic practice. For people whose careers can't afford either one alone.",
      scroll: 'Scroll',
      dossier: ['Croatian', 'MSc HR · EFZG', 'P&G · Hitachi · dm', 'ICF · Phyto / 07·2026'],
      portraitAlt: 'Vedra Regul Erent-Ondrušek — portrait',
    },
    manifesto: {
      eyebrow: '02 / Manifesto',
      headline: "Your life is a system. Stop pretending it isn't.",
      lines: [
        'You run P&Ls at work. You stakeholder-map the boardroom. You execute 100-day plans.',
        'Then you go home and your nervous system runs the show — and nobody wrote it a brief.',
        'Ten years inside corporate HR taught me what works.',
        'Ten more years with the body taught me why it still doesn’t.',
        'Most coaches pick a side. You can’t afford to.',
      ],
      emphasis: 'Most coaches pick a side. You can’t afford to.',
    },
    marquee: {
      words: [
        'RACI',
        'Somatic',
        'Kanban',
        'Breath',
        'Stakeholders',
        'Regulation',
        '100-day',
        'Phyto',
        'P&L',
        'Recovery',
        'Authority',
        'Embodiment',
        'Execution',
        'Nervous system',
      ],
    },
    approach: {
      eyebrow: '03 / Approach',
      headline: 'Two toolkits. One operator.',
      left: {
        label: '01',
        tag: 'From HR',
        title: 'Corporate rigor',
        body: 'RACI matrices. Kanban. 100-day plans. Stakeholder maps. Performance diagnostics. Ten years of what works inside P&G, Hitachi, Transcom, dm-drogeriemarkt — applied to problems that don’t fit a spreadsheet.',
      },
      right: {
        label: '02',
        tag: 'From the body',
        title: 'Somatic practice',
        body: 'Nervous-system regulation. Breath work. Plant-based recovery. Embodiment protocols. The operator’s body, not the operator’s calendar — because one without the other eventually breaks.',
      },
      unifier: 'Most coaches choose one. You need both.',
    },
    gallery: {
      eyebrow: '04 / Field notes',
      headline: 'Where the work lives.',
      caption: 'A practice has weather, hours, and a room. These are the edges of mine.',
      items: [
        {
          label: '01 / Morning',
          title: 'Before the inbox opens.',
          body: 'Notebook, tea, thirty minutes nobody else owns.',
          theme: 'ochre' as PlaceholderTheme,
          illustration: 'sunrise' as Illustration,
        },
        {
          label: '02 / Field',
          title: 'Plants that do the repair work.',
          body: 'Phyto protocols calibrated to actual nervous systems, not marketing promises.',
          theme: 'moss' as PlaceholderTheme,
          illustration: 'botanical' as Illustration,
        },
        {
          label: '03 / City',
          title: 'Zagreb, 10000.',
          body: 'Where the practice lives. International clients remote, locals in the room.',
          theme: 'moss-ochre' as PlaceholderTheme,
          illustration: 'horizon' as Illustration,
        },
      ],
    },
    services: {
      eyebrow: '05 / Services',
      headline: 'What you leave with.',
      hint: 'Click any service to read the full shape.',
      items: [
        {
          outcome: 'Walk into a new role already in command.',
          body: 'Day-one authority protocol. 90-day execution plan. Stakeholder map before your first 1:1.',
          scope: 'First 100 Days · Authority Accelerator',
          format: '1:1 · 100 days',
          who: 'Senior operators stepping into visibility. Internal promotions where the bar just moved. External hires entering politically unfamiliar ground.',
          beats: [
            { label: 'Week 0', text: 'Stakeholder inventory. We map every relationship that matters, in order of leverage.' },
            { label: 'Week 2', text: 'Authority move. One calibrated decision that establishes what you are going to be in this role.' },
            { label: 'Week 6', text: 'Execution mid-check. A written review: what’s working, what’s drifting, what to correct.' },
            { label: 'Week 14', text: 'Outcome audit. The 90-day plan against reality. What’s next.' },
          ],
          deliverables: [
            'A written 100-day plan',
            'Stakeholder map and leverage model',
            'Three weekly 1:1s embedded in your calendar',
            'Somatic regulation protocols for when the nervous system spikes',
          ],
          principle: 'Authority is established by day 14. Not argued for on day 90.',
        },
        {
          outcome: 'Diagnose what’s breaking your week in fifteen minutes.',
          body: 'Energy audit. Calendar autopsy. One lever to pull this week. Free first session.',
          scope: 'High-Performance Audit',
          format: '1:1 · 15 min trial',
          who: 'Anyone high-functioning who can feel the system creaking. Before burnout, while you still have choice.',
          beats: [
            { label: 'The audit', text: 'Fifteen minutes on the phone. I ask you seven questions.' },
            { label: 'The map', text: 'We locate the single leak draining the most energy.' },
            { label: 'The lever', text: 'One specific action to take this week. Smallest possible.' },
            { label: 'The follow-up', text: 'Check-in after seven days. We iterate or escalate.' },
          ],
          deliverables: [
            'Written audit summary',
            'The one lever — named and dated',
            'A before/after energy baseline',
            'Option to continue into full engagement',
          ],
          principle: 'The leak is never where the noise is.',
        },
        {
          outcome: 'Rebuild a career you stopped believing in.',
          body: 'For the mid-career stall. Positioning, inventory, next move — with the numbers to back it.',
          scope: 'Individual Career Counseling',
          format: '1:1 · ongoing',
          who: 'Mid-career operators who outgrew their role but can’t see the next. Founders who realized the company isn’t the dream anymore. Anyone negotiating their own next five years.',
          beats: [
            { label: 'Inventory', text: 'We list everything — skills, currencies, debts, hidden assets.' },
            { label: 'Positioning', text: 'What market is this person? Where is the undervalued seat?' },
            { label: 'Scenarios', text: 'Three credible next moves with numbers attached.' },
            { label: 'The ask', text: 'What you need to make the move — people, runway, training, evidence.' },
          ],
          deliverables: [
            'Career inventory document',
            'Three modeled scenarios with risk profiles',
            'Ask list by priority',
            'Monthly 1:1s for the transition window',
          ],
          principle: 'A stalled career is almost never about the market. It is about the unrevised story.',
        },
        {
          outcome: 'Run your household like it deserves a strategy.',
          body: 'RACI your family. Kanban the logistics. For couples and operators whose home runs on wishful thinking.',
          scope: 'Strategic Household Operations',
          format: '1:1 or couple · project-based',
          who: 'Couples where one person is carrying invisible operations. Families navigating illness, moves, or school transitions. Operators who built companies and then tried to wing it at home.',
          beats: [
            { label: 'Audit', text: 'What gets done, by whom, on what cadence. Unlogged labor surfaces.' },
            { label: 'Ownership', text: 'RACI matrix by household domain. The invisible becomes named.' },
            { label: 'Cadence', text: 'Weekly ops meetings. Quarterly reviews. A calendar that holds the household.' },
            { label: 'Protocols', text: 'Nervous-system interventions for when plan meets reality.' },
          ],
          deliverables: [
            'Household RACI document',
            'Weekly ops meeting template',
            'Quarterly review protocol',
            'Custom stress-recovery practices for the partnership',
          ],
          principle: 'A home without strategy is a home run by whoever breaks first.',
        },
        {
          outcome: 'Keep functioning when life doesn’t.',
          body: 'Illness. Divorce. Bereavement. Business continuity for the things business doesn’t name.',
          scope: 'Crisis Support',
          format: 'Bespoke',
          who: 'People in the middle of a crisis they did not choose. Partners, parents, and operators who still have people depending on them.',
          beats: [
            { label: 'Stabilize', text: 'What absolutely must continue. What can be paused. What must be delegated now.' },
            { label: 'Continuity', text: 'Short-horizon operational plan — two weeks at a time.' },
            { label: 'Support', text: 'Who does what, when, and how to ask.' },
            { label: 'Care', text: 'Nervous-system, breath and phytotherapy practices calibrated to exhaustion, not performance.' },
          ],
          deliverables: [
            'Continuity plan in writing',
            'Support architecture map',
            'Weekly 1:1s for as long as needed',
            'Direct phone access for acute moments',
          ],
          principle: 'You don’t think your way out of a crisis. You operate through it — while you heal.',
        },
      ],
      pricing: 'Pricing on application.',
      labels: {
        who: 'Who it’s for',
        beats: 'What happens',
        deliverables: 'What you leave with',
        principle: 'Principle',
        expand: 'Open',
        collapse: 'Close',
      },
    },
    story: {
      eyebrow: '07 / How I got here',
      headline: 'How I got here.',
      paragraphs: [
        'When I was nineteen, my father was paralyzed. I raised three younger brothers through the rest of my teens. You either build systems or you drown. I built systems.',
        'Ten years in corporate HR followed — P&G, Hitachi, Transcom, dm-drogeriemarkt. I learned what structure can do, and where it stops working. MA in HR management from EFZG. Contemporary dance. Phytotherapy. Every time the tools ran out, I went to find more.',
        'Now I do both at once. Corporate rigor. Nervous-system work. Plant-based recovery. One operator.',
      ],
      credentials: 'ICF certification completes July 2026. Phytotherapy certification completes July 2026.',
      portraitAlt: 'Vedra Regul Erent-Ondrušek',
    },
    testimonials: {
      eyebrow: '08 / Proof',
      headline: 'No testimonials yet. On purpose.',
      body: 'The 2026 founding cohort runs through the end of the year. Early clients shape how this practice gets built — and get my undivided attention while the calendar isn’t full. You’ll see testimonials here when I’ve earned them.',
    },
    principles: {
      eyebrow: '09 / Principles',
      headline: 'The operating manual.',
      sub: 'Six rules that run under every engagement. If you disagree with most of them, we are probably not a fit.',
      items: [
        {
          title: 'Authority precedes permission.',
          body: 'You don’t earn the right to lead by asking for it. You establish it, precisely, before anyone checks.',
          tag: 'Leadership',
        },
        {
          title: 'The body keeps your schedule.',
          body: 'If your nervous system says no, your calendar is lying. Fix the body, or the plan fails.',
          tag: 'Somatic',
        },
        {
          title: 'A career is a system, not a ladder.',
          body: 'Ladders have rungs. Systems have leverage points. Find yours.',
          tag: 'Career',
        },
        {
          title: 'Crisis runs on structure.',
          body: 'The only thing that works when nothing else does is cadence. Plan the next two weeks. Then the next two.',
          tag: 'Crisis',
        },
        {
          title: 'Generalists with discipline beat specialists without.',
          body: 'Two toolkits inside one operator outperform one toolkit inside a purist, every time.',
          tag: 'Practice',
        },
        {
          title: 'The loudest complaint is never the leak.',
          body: 'Symptoms are downstream. Diagnose where the energy actually goes, not where it gets noticed.',
          tag: 'Diagnostic',
        },
      ],
    },
    contact: {
      eyebrow: '10 / Contact',
      headline: 'Let’s write.',
      sub: 'The practice is new. I prefer letters to forms — and I reply personally, usually within 48 hours.',
      paths: [
        {
          label: '01 / Fast',
          title: 'Fifteen-minute audit.',
          body: 'Free diagnostic. Seven questions, three minutes, one written diagnosis. No pitch.',
          cta: 'Open the audit',
          href: '/audit',
        },
        {
          label: '02 / Open',
          title: 'Write a letter.',
          body: 'Short or long. Specific or not. I read all of them.',
          cta: 'Email me',
          href: 'mailto:vedra.re.ondrusek@gmail.com',
        },
        {
          label: '03 / Deep',
          title: 'Founding engagement.',
          body: 'For people ready to go deeper. Twelve seats through 2026. Application, not booking.',
          cta: 'Write the letter',
          href: '/apply',
        },
      ],
      direct: {
        label: 'Or direct',
        email: 'vedra.re.ondrusek@gmail.com',
        phone: '+385 95 922 9547',
        location: 'Zagreb, Croatia',
      },
      note: {
        eyebrow: 'Or',
        headline: 'Send a note now.',
        sub: 'One field. No structure required.',
        placeholder: 'What’s on your mind?',
        submit: 'Send',
        sending: 'Sending…',
        sent: 'Sent. I’ll come back to you within two working days.',
        fromLabel: 'From',
        fromPlaceholder: 'name@domain.com',
      },
    },
    footer: {
      tagline: 'Practice of Vedra Regul Erent-Ondrušek',
      copyright: '© 2026 Trillian HR',
      legal: 'Zagreb, Croatia · OIB on request',
    },
  },

  hr: {
    meta: {
      wordmark: 'Trillian HR',
      location: 'Zagreb',
      practitioner: 'Vedra Regul Erent-Ondrušek',
    },
    nav: {
      approach: 'Pristup',
      services: 'Usluge',
      story: 'Priča',
      principles: 'Principi',
      contact: 'Kontakt',
      apply: 'Napiši',
    },
    hero: {
      eyebrow: '01 / Bok',
      line1: 'Nisam tipičan coach.',
      line2Prefix: 'Vjerojatno sam',
      line2Suffix: '.',
      rotating: ['gora', 'teža', 'čudnija', 'stranija'],
      sub: 'HR metodologija susreće somatsku praksu. Za ljude čije karijere ne mogu priuštiti ni jedno ni drugo samo.',
      scroll: 'Skrolaj',
      dossier: ['Hrvatica', 'MSc HR · EFZG', 'P&G · Hitachi · dm', 'ICF · Fito / 07·2026'],
      portraitAlt: 'Vedra Regul Erent-Ondrušek — portret',
    },
    manifesto: {
      eyebrow: '02 / Manifest',
      headline: 'Tvoj život je sustav. Prestani se pretvarati da nije.',
      lines: [
        'Vodiš P&L na poslu. Mapiraš dionike u sali. Izvršavaš plan prvih 100 dana.',
        'Onda dođeš kući i tvoj živčani sustav vodi show — i nitko mu nije napisao brief.',
        'Deset godina korporativnog HR-a naučilo me što funkcionira.',
        'Sljedećih deset s tijelom — zašto i dalje ne funkcionira.',
        'Većina coacheva bira stranu. Ti si ne možeš priuštiti.',
      ],
      emphasis: 'Većina coacheva bira stranu. Ti si ne možeš priuštiti.',
    },
    marquee: {
      words: [
        'RACI',
        'Somatsko',
        'Kanban',
        'Dah',
        'Dionici',
        'Regulacija',
        '100 dana',
        'Fito',
        'P&L',
        'Oporavak',
        'Autoritet',
        'Utjelovljenje',
        'Izvršenje',
        'Živčani sustav',
      ],
    },
    approach: {
      eyebrow: '03 / Pristup',
      headline: 'Dva alata. Jedan operator.',
      left: {
        label: '01',
        tag: 'Iz HR-a',
        title: 'Korporativna strogost',
        body: 'RACI matrice. Kanban. Planovi prvih 100 dana. Mape dionika. Dijagnostika učinka. Deset godina onoga što funkcionira u P&G-u, Hitachi-ju, Transcom-u, dm-u — primijenjeno na probleme koji ne stanu u tablicu.',
      },
      right: {
        label: '02',
        tag: 'Iz tijela',
        title: 'Somatska praksa',
        body: 'Regulacija živčanog sustava. Disanje. Biljna podrška oporavku. Protokoli za tijelo. Tijelo operatora, ne kalendar operatora — jer jedno bez drugog prije ili kasnije puca.',
      },
      unifier: 'Većina coacheva bira jedno. Tebi trebaju oba.',
    },
    gallery: {
      eyebrow: '04 / Bilješke s terena',
      headline: 'Gdje se posao događa.',
      caption: 'Praksa ima vrijeme, sate i prostoriju. Ovo su rubovi moje.',
      items: [
        {
          label: '01 / Jutro',
          title: 'Prije nego što se inbox otvori.',
          body: 'Bilježnica, čaj, tridesetak minuta koje nitko drugi ne posjeduje.',
          theme: 'ochre' as PlaceholderTheme,
          illustration: 'sunrise' as Illustration,
        },
        {
          label: '02 / Polje',
          title: 'Biljke koje rade popravak.',
          body: 'Fito protokoli kalibrirani na stvarni živčani sustav, ne na marketinška obećanja.',
          theme: 'moss' as PlaceholderTheme,
          illustration: 'botanical' as Illustration,
        },
        {
          label: '03 / Grad',
          title: 'Zagreb, 10000.',
          body: 'Gdje praksa živi. Internacionalni klijenti remote, lokalni u sobi.',
          theme: 'moss-ochre' as PlaceholderTheme,
          illustration: 'horizon' as Illustration,
        },
      ],
    },
    services: {
      eyebrow: '05 / Usluge',
      headline: 'S čime odlaziš.',
      hint: 'Klikni uslugu za cijeli oblik.',
      items: [
        {
          outcome: 'Uđi u novu ulogu već s autoritetom.',
          body: 'Protokol autoriteta od prvog dana. Plan izvršenja za 90 dana. Mapa dionika prije prvog 1:1 sastanka.',
          scope: 'Prvih 100 dana · Akcelerator autoriteta',
          format: '1:1 · 100 dana',
          who: 'Viši operatori koji ulaze u ulogu s vidljivošću. Interne promocije gdje se letvica podigla. Vanjski angažmani u politički nepoznat teren.',
          beats: [
            { label: 'Tjedan 0', text: 'Popis dionika. Mapiramo svaki odnos koji je bitan — po polugi.' },
            { label: 'Tjedan 2', text: 'Autoritetni potez. Jedna kalibrirana odluka koja postavlja tko ćeš biti u ovoj ulozi.' },
            { label: 'Tjedan 6', text: 'Srednji check-in. Pisano: što funkcionira, što drfta, što ispraviti.' },
            { label: 'Tjedan 14', text: 'Revizija rezultata. 90-dnevni plan nasuprot stvarnosti. Što dalje.' },
          ],
          deliverables: [
            'Napisan plan prvih 100 dana',
            'Mapa dionika i model poluge',
            'Tri tjedna 1:1 unutar kalendara',
            'Somatski protokoli za trenutke kad živčani sustav skoči',
          ],
          principle: 'Autoritet se postavlja do 14. dana. Ne argumentira na 90.',
        },
        {
          outcome: 'Utvrdi što ti razbija tjedan u petnaest minuta.',
          body: 'Audit energije. Analiza kalendara. Jedna poluga koju ovaj tjedan povučeš. Prva sesija besplatna.',
          scope: 'Audit visokog učinka',
          format: '1:1 · 15 min proba',
          who: 'Bilo tko visoko funkcionalan tko osjeća da sustav škripi. Prije izgaranja, dok još imaš izbor.',
          beats: [
            { label: 'Audit', text: 'Petnaest minuta na telefonu. Postavim ti sedam pitanja.' },
            { label: 'Karta', text: 'Lociramo curenje koje najviše crpi energiju.' },
            { label: 'Poluga', text: 'Jedna konkretna akcija za ovaj tjedan. Najmanja moguća.' },
            { label: 'Follow-up', text: 'Provjera nakon sedam dana. Iteriramo ili eskaliramo.' },
          ],
          deliverables: [
            'Pisani sažetak audita',
            'Jedna poluga — imenovana i datirana',
            'Prije/poslije bazna linija energije',
            'Opcija nastavka u punom angažmanu',
          ],
          principle: 'Curenje nije tamo gdje je buka.',
        },
        {
          outcome: 'Ponovno izgradi karijeru u koju si prestao vjerovati.',
          body: 'Za sredinu karijere u zastoju. Pozicioniranje, inventura, sljedeći potez — s brojkama koje drže.',
          scope: 'Individualno savjetovanje o karijeri',
          format: '1:1 · kontinuirano',
          who: 'Operatori u sredini karijere koji su prerasli ulogu ali ne vide sljedeću. Osnivači koji su shvatili da tvrtka više nije san. Bilo tko tko pregovara svojih sljedećih pet godina.',
          beats: [
            { label: 'Inventura', text: 'Popisujemo sve — vještine, valute, dugove, skrivene resurse.' },
            { label: 'Pozicioniranje', text: 'Koje je tržište ova osoba? Gdje je podcijenjeno sjedalo?' },
            { label: 'Scenariji', text: 'Tri vjerodostojna sljedeća poteza s brojkama.' },
            { label: 'Zahtjev', text: 'Što trebaš za potez — ljudi, runway, obuka, dokazi.' },
          ],
          deliverables: [
            'Dokument karijerne inventure',
            'Tri modelirana scenarija s rizikom',
            'Lista zahtjeva po prioritetu',
            'Mjesečni 1:1 kroz prijelaz',
          ],
          principle: 'Zastoj u karijeri gotovo nikad nije tržište. To je nerevidirana priča.',
        },
        {
          outcome: 'Vodi domaćinstvo kao da zaslužuje strategiju.',
          body: 'RACI za obitelj. Kanban za logistiku. Za parove i operatore čiji dom radi na dobroj volji.',
          scope: 'Strateške operacije domaćinstva',
          format: '1:1 ili par · projektno',
          who: 'Parovi gdje jedna osoba nosi nevidljive operacije. Obitelji koje navigiraju bolest, selidbu ili školske tranzicije. Operatori koji su gradili tvrtke i pokušali snaći se doma na sreću.',
          beats: [
            { label: 'Audit', text: 'Što se radi, tko radi, kojom kadencom. Neregistrirani rad na površinu.' },
            { label: 'Vlasništvo', text: 'RACI po domenama doma. Nevidljivo se imenuje.' },
            { label: 'Kadenca', text: 'Tjedni ops sastanci. Kvartalne revizije. Kalendar koji drži dom.' },
            { label: 'Protokoli', text: 'Intervencije za živčani sustav kad plan susreće stvarnost.' },
          ],
          deliverables: [
            'RACI dokument domaćinstva',
            'Predložak tjednog ops sastanka',
            'Protokol kvartalne revizije',
            'Prilagođene prakse oporavka partnerstva',
          ],
          principle: 'Dom bez strategije vodi onaj tko prvi pukne.',
        },
        {
          outcome: 'Nastavi funkcionirati kad život ne funkcionira.',
          body: 'Bolest. Razvod. Gubitak. Kontinuitet za stvari koje posao ne imenuje.',
          scope: 'Podrška u krizi',
          format: 'Po mjeri',
          who: 'Ljudi usred krize koju nisu izabrali. Partneri, roditelji, operatori koji i dalje imaju ljude o njima ovisne.',
          beats: [
            { label: 'Stabilizacija', text: 'Što apsolutno mora nastaviti. Što se može pauzirati. Što se mora delegirati sada.' },
            { label: 'Kontinuitet', text: 'Kratkoročni operativni plan — dva tjedna odjednom.' },
            { label: 'Podrška', text: 'Tko radi što, kada, i kako tražiti.' },
            { label: 'Skrb', text: 'Prakse živčanog sustava, disanja i fitoterapije kalibrirane za iscrpljenost, ne učinak.' },
          ],
          deliverables: [
            'Pisani plan kontinuiteta',
            'Karta podrške',
            'Tjedni 1:1 koliko god treba',
            'Direktan telefonski pristup za akutne trenutke',
          ],
          principle: 'Iz krize se ne razmišlja. Operira se kroz nju — dok se ozdravljuje.',
        },
      ],
      pricing: 'Cijena na upit.',
      labels: {
        who: 'Za koga je',
        beats: 'Što se događa',
        deliverables: 'S čime odlaziš',
        principle: 'Princip',
        expand: 'Otvori',
        collapse: 'Zatvori',
      },
    },
    story: {
      eyebrow: '07 / Kako sam došla dovde',
      headline: 'Kako sam došla dovde.',
      paragraphs: [
        'S devetnaest, moj otac je doživio paralizu. Trojicu mlađe braće odgajala sam do kraja tinejdžerskih godina. Ili gradiš sustave ili se utapljaš. Gradila sam sustave.',
        'Uslijedilo je deset godina u korporativnom HR-u — P&G, Hitachi, Transcom, dm-drogeriemarkt. Naučila sam što struktura može i gdje prestaje raditi. Magisterij iz HR menadžmenta na EFZG. Suvremeni ples. Fitoterapija. Svaki put kad su alati presušili, otišla sam pronaći nove.',
        'Sad radim oboje istovremeno. Korporativna strogost. Rad na živčanom sustavu. Biljni oporavak. Jedan operator.',
      ],
      credentials: 'ICF certifikacija završava u srpnju 2026. Certifikat iz fitoterapije u srpnju 2026.',
      portraitAlt: 'Vedra Regul Erent-Ondrušek',
    },
    testimonials: {
      eyebrow: '08 / Dokaz',
      headline: 'Bez svjedočanstava. Zasad. Namjerno.',
      body: 'Osnivačka generacija 2026. traje do kraja godine. Rani klijenti oblikuju kako ova praksa izgleda — i dobivaju moju nepodijeljenu pažnju dok kalendar nije pun. Svjedočanstva ćeš vidjeti kad ih zaslužim.',
    },
    principles: {
      eyebrow: '09 / Principi',
      headline: 'Operativni priručnik.',
      sub: 'Šest pravila koja idu ispod svakog angažmana. Ako se ne slažeš s većinom, vjerojatno nismo dobar par.',
      items: [
        {
          title: 'Autoritet prethodi dozvoli.',
          body: 'Pravo da vodiš ne zaslužuješ traženjem. Uspostavljaš ga, precizno, prije nego što itko provjeri.',
          tag: 'Vodstvo',
        },
        {
          title: 'Tijelo drži raspored.',
          body: 'Ako ti živčani sustav kaže ne, kalendar laže. Popravi tijelo, ili plan pada.',
          tag: 'Somatsko',
        },
        {
          title: 'Karijera je sustav, ne ljestve.',
          body: 'Ljestve imaju prečke. Sustavi imaju točke poluge. Pronađi svoje.',
          tag: 'Karijera',
        },
        {
          title: 'Kriza funkcionira na strukturi.',
          body: 'Jedino što radi kad ništa drugo ne radi je kadenca. Isplaniraj sljedeća dva tjedna. Pa sljedeća dva.',
          tag: 'Kriza',
        },
        {
          title: 'Generalisti s disciplinom pobjeđuju specijaliste bez.',
          body: 'Dva alata u jednom operatoru nadmašuju jedan alat kod purista, svaki put.',
          tag: 'Praksa',
        },
        {
          title: 'Najglasnija žalba nikad nije curenje.',
          body: 'Simptomi su nizvodno. Dijagnosticiraj gdje energija stvarno odlazi, ne gdje se primjećuje.',
          tag: 'Dijagnoza',
        },
      ],
    },
    contact: {
      eyebrow: '10 / Kontakt',
      headline: 'Napišimo.',
      sub: 'Praksa je nova. Više volim pisma od obrazaca — odgovaram osobno, obično unutar 48 sati.',
      paths: [
        {
          label: '01 / Brzo',
          title: 'Petnaestminutni audit.',
          body: 'Besplatna dijagnoza. Sedam pitanja, tri minute, jedna pisana dijagnoza. Bez prodaje.',
          cta: 'Otvori audit',
          href: '/hr/audit',
        },
        {
          label: '02 / Otvoreno',
          title: 'Napiši pismo.',
          body: 'Kratko ili dugo. Konkretno ili ne. Čitam sva.',
          cta: 'Pošalji email',
          href: 'mailto:vedra.re.ondrusek@gmail.com',
        },
        {
          label: '03 / Dublje',
          title: 'Osnivački angažman.',
          body: 'Za one spremne ići dublje. Dvanaest mjesta do kraja 2026. Aplikacija, ne rezervacija.',
          cta: 'Napiši pismo',
          href: '/hr/apply',
        },
      ],
      direct: {
        label: 'Ili direktno',
        email: 'vedra.re.ondrusek@gmail.com',
        phone: '+385 95 922 9547',
        location: 'Zagreb, Hrvatska',
      },
      note: {
        eyebrow: 'Ili',
        headline: 'Pošalji poruku sada.',
        sub: 'Jedno polje. Bez strukture.',
        placeholder: 'Što ti je na umu?',
        submit: 'Pošalji',
        sending: 'Šaljem…',
        sent: 'Poslano. Javim se u roku od dva radna dana.',
        fromLabel: 'Od',
        fromPlaceholder: 'ime@domena.com',
      },
    },
    footer: {
      tagline: 'Praksa Vedre Regul Erent-Ondrušek',
      copyright: '© 2026 Trillian HR',
      legal: 'Zagreb, Hrvatska · OIB na upit',
    },
  },
} as const

export type Strings = typeof strings.en
