// All site copy lives here. Croatian is the source of truth (from Vedra's brief);
// English is a first-draft translation for Vedra to review.
//
// MISSING COPY flags mark blocks awaiting input from Vedra. Search for
// `MISSING COPY` to see what still needs real text.

export type Lang = 'en' | 'hr'

export type Illustration = 'leaf' | 'ripple' | 'wave' | 'grid' | 'curve' | 'botanical' | 'sunrise' | 'horizon' | 'none'
export type PlaceholderTheme = 'moss-ochre' | 'moss' | 'ochre' | 'neutral'

export const strings = {
  en: {
    meta: {
      wordmark: 'Trillian',
      subtitle: 'coaching',
      location: 'Zagreb',
      practitioner: 'Vedra Regul Erent-Ondrušek',
    },
    nav: {
      home: 'Home',
      about: 'About',
      packages: 'Packages',
      approach: 'Approach',
      contact: 'Contact',
      blog: 'Blog',
      apply: "15′ Audit",
      // legacy keys — kept so older components still type-check
      services: 'Packages',
      story: 'About',
      principles: 'Principles',
    },
    hero: {
      eyebrow: '01 / Hello',
      line1: 'Run your life',
      line2Prefix: 'like you run a',
      line2Suffix: '.',
      rotating: ['business', 'company', 'team', 'system'],
      sub: 'Corporate tools applied to everyday life. Corporate methodology meets performance biology. Structure and measurable results.',
      scroll: 'Scroll',
      dossier: ['Croatian', 'MSc HR · EFZG', 'P&G · Hitachi · dm', 'ICF · Phyto / 07·2026'],
      portraitAlt: 'Vedra Regul Erent-Ondrušek — portrait',
      ctaLabel: 'Run the 15-minute audit',
      ctaMicro: 'Free · 7 questions · 3 minutes',
    },
    manifesto: {
      eyebrow: '02 / Manifesto',
      headline: 'Not the coaching type?',
      lines: [
        "My method isn't sitting on a couch talking about problems.",
        'This is implementation of concrete tools — Organizational Performance Model, Kanban, RACI, Stakeholder mapping — inside your private life.',
        'Optimize your most important resources: Time, Energy, Focus.',
        "Don't improvise where you don't have to.",
        "If your business has KPIs and clear roles, why doesn't your private life?",
        'Install an operating system that links corporate logic and biological regeneration.',
      ],
      emphasis: 'Install an operating system that links corporate logic and biological regeneration.',
    },
    marquee: {
      words: [
        'RACI',
        'OPM',
        'Kanban',
        'Phytotherapy',
        'BCP',
        'Power posture',
        '100-day plan',
        'Stakeholders',
        '80/20',
        'Nervous system',
        'Somatic',
        'Executive',
        'Recovery',
        'Authority',
      ],
    },
    approach: {
      eyebrow: '03 / My approach',
      headline: 'Four tools. One operator.',
      pillars: [
        {
          label: '01',
          tag: 'Corporate tools',
          title: 'Proven corporate tools, applied privately.',
          body: 'Process analysis (where does your time actually go?), RACI matrices (who is accountable at home?), OPM (how to keep moving after change?), 80/20 (highest benefit for lowest input?), and more — tailored to you. Goal: maximum efficiency, minimum wasted energy.',
        },
        {
          label: '02',
          tag: 'Coaching',
          title: 'Present-and-future, not past.',
          body: "Coaching focuses on present and future and asks sharp questions — I support you in finding your own answers to life decisions and professional challenges. Consulting lets me say what I think should be done. I attend and love psychotherapy but I'm not a licensed therapist and won't treat diagnoses. Here we do coaching and consulting.",
        },
        {
          label: '03',
          tag: 'Phytotherapy',
          title: 'A tincture with your name on the bottle.',
          body: "Croatia is rich in plants with active compounds that support immunity, sleep and relaxation. As a certified phyto-aromatherapist I've studied their chemistry and love making fresh, potent preparations. Shelf supplements can't match a freshly made, individualized phyto preparation. Note: I don't fill batch orders and don't sell preparations to treat diseases.",
        },
        {
          label: '04',
          tag: 'Body work',
          title: 'Power posture and regulation through the body.',
          body: "[AI draft — Vedra to finalize.] The body remembers what the calendar demands. Fifteen years inside fitness and contemporary dance taught me protocols for power posture — the body position that signals authority in under a second — and for regulating through movement: short breath and micro-movement sequences that release tension in shoulders, neck, and diaphragm. You don't need a yoga class before the meeting. You need two minutes of precise practice so the body receives the signal that it's safe.",
        },
      ],
      unifier: 'Four disciplines, one operator. You need all of them.',
    },
    gallery: {
      eyebrow: '04 / Field notes',
      headline: 'Where the work lives.',
      caption: 'A practice has weather, hours, and a room. These are the edges of mine.',
      items: [
        {
          label: '01 / Morning',
          title: 'Before the inbox opens.',
          body: 'Notebook, tea, thirty minutes nobody else owns.',
          theme: 'ochre' as PlaceholderTheme,
          illustration: 'sunrise' as Illustration,
        },
        {
          label: '02 / Field',
          title: 'Plants that do the repair work.',
          body: 'Phyto protocols calibrated to actual nervous systems, not marketing promises.',
          theme: 'moss' as PlaceholderTheme,
          illustration: 'botanical' as Illustration,
        },
        {
          label: '03 / City',
          title: 'Zagreb, 10000.',
          body: 'Where the practice lives. International clients remote, locals in the room.',
          theme: 'moss-ochre' as PlaceholderTheme,
          illustration: 'horizon' as Illustration,
        },
      ],
    },
    services: {
      eyebrow: '04 / Packages',
      headline: 'Four programs for the operator.',
      hint: 'Click a package to see the sessions inside. Pricing on request.',
      items: [
        {
          outcome: 'Walk into a new role already in command.',
          body: 'A program for people preparing for a promotion — or who just got one. Authority established by week two, not month three.',
          scope: 'First 100 Days: Authority Accelerator',
          format: '1:1 · program',
          who: 'Senior operators stepping into visibility. Internal promotions where the bar just moved. External hires entering politically unfamiliar ground.',
          beats: [
            { label: 'Session 01', text: 'Stakeholder Mapping' },
            { label: 'Session 02', text: 'First Wins strategy' },
            { label: 'Session 03', text: 'Somatic Leadership' },
            { label: 'Session 04', text: 'Phyto protocol (as needed)' },
            { label: 'Session 05', text: 'Weekly 1:1 review' },
            { label: 'Session 06', text: '90-day outcome audit' },
          ],
          deliverables: [
            'Written 100-day plan and stakeholder map',
            'Direct phone access for the first 30 days',
            'Somatic regulation protocols for high-pressure moments',
          ],
          principle: 'Authority is established by day 14, not argued for on day 90.',
        },
        {
          outcome: 'Run your household like it deserves a strategy.',
          body: 'Manage a household with the precision of a successful company. Less friction, more shared energy, clearer ownership.',
          scope: 'Strategic Household Operations',
          format: '1:1 or couple · project-based',
          who: 'Couples where one person is carrying invisible operations. Families navigating illness, moves, or school transitions. Operators who built companies and then tried to wing it at home.',
          beats: [
            { label: 'Session 01', text: 'Family RACI matrix' },
            { label: 'Session 02', text: 'Domestic Kanban' },
            { label: 'Session 03', text: 'Shared Vision board' },
            { label: 'Session 04', text: 'Weekly ops meeting template' },
            { label: 'Session 05', text: 'Quarterly review' },
            { label: 'Session 06', text: 'Somatic protocol for household stress' },
          ],
          deliverables: [
            'Household RACI document and weekly-ops template',
            'Family BCP (Business Continuity Plan) template',
            'Custom stress-recovery practices for the partnership',
          ],
          principle: 'A home without strategy is a home run by whoever breaks first.',
        },
        {
          outcome: 'Diagnose what is breaking your week.',
          body: 'For professionals who can feel their energy leaking. Energy P&L, calendar autopsy, posture, phyto support — calibrated to the actual leak.',
          scope: 'High-Performance Audit',
          format: '1:1 · 15 min free start',
          who: 'High-functioning people who can feel the system creaking. Before burnout, while you still have choice.',
          beats: [
            { label: 'Session 01', text: 'Energy Profit & Loss analysis' },
            { label: 'Session 02', text: 'Performance Gap analysis' },
            { label: 'Session 03', text: 'Executive posture & authority' },
            { label: 'Session 04', text: 'Phyto protocol' },
            { label: 'Session 05', text: 'Calendar autopsy' },
            { label: 'Session 06', text: '30-day follow-up' },
          ],
          deliverables: [
            'Written audit summary with one named lever',
            'Individualized phyto preparation (two-week supply)',
            'Before/after energy baseline',
          ],
          principle: 'The leak is never where the noise is.',
        },
        {
          outcome: 'Keep operating through a family crisis.',
          body: 'Illness. Bereavement. Divorce. Apply corporate Business Continuity Planning (BCP) and Organization Performance Model (OPM) to private life at moments of extreme stress.',
          scope: 'Crisis Support · I deserve support',
          format: 'Bespoke · crisis protocol',
          who: 'People in the middle of a crisis they did not choose. Partners, parents, operators who still have people depending on them.',
          beats: [
            { label: 'Session 01', text: 'Business Continuity Plan (BCP)' },
            { label: 'Session 02', text: 'OPM for crisis' },
            { label: 'Session 03', text: 'Support architecture map' },
            { label: 'Session 04', text: 'Weekly 1:1s' },
            { label: 'Session 05', text: 'Phyto protocol for exhaustion' },
            { label: 'Session 06', text: 'Direct phone access' },
          ],
          deliverables: [
            'Written continuity plan and support architecture',
            'Bespoke cadence — no session limit',
            'Direct phone access for acute moments',
          ],
          principle: 'You don\'t think your way out of a crisis. You operate through it — while you heal.',
        },
      ],
      pricing: 'Pricing on request. Vedra will publish three fixed packages with clear session counts soon.',
      labels: {
        who: 'Who it\'s for',
        beats: 'Sessions',
        deliverables: 'Something additional',
        principle: 'Principle',
        expand: 'Open',
        collapse: 'Close',
      },
    },
    story: {
      eyebrow: '05 / About',
      headline: 'You and me.',
      paragraphs: [
        "I'm not a typical coach. I'm probably worse.",
        'Behind me: 10 years of corporate HR — four of them at Procter & Gamble, the global gold standard for systems and process. BA in sociology and German, MSc in HR management from EFZG. Currently training for ICF-accredited Executive Coach certification.',
        "I'm also a certified phyto-aromatherapist, using the science of plant extracts to build protocols for biology and health — plus a certified fitness instructor, using body knowledge for power posture and stress regulation.",
        'What does that mean for you? I offer you proven tools. Why am I worse? Because I expect results.',
      ],
      credentials: 'ICF certification · July 2026. Phytotherapy certification · July 2026.',
      portraitAlt: 'Vedra Regul Erent-Ondrušek',
      moreLabel: 'More about me',
    },
    about: {
      eyebrow: '05 / About me',
      headline: 'Experience and academic path.',
      intro: "One day, after an exhausting stretch of life, my psychotherapist told me I'd be an excellent coach for working with people. There is no higher endorsement than from a woman who knows my darkest shadow self. Here's the tangible evidence, too.",
      slides: [
        {
          num: '01',
          title: 'Corporate Special Forces',
          body: 'Ten years of corporate work — four at Procter & Gamble, the rest at Hitachi, Transcom and dm-drogeriemarkt. P&G is the global gold standard for systems and process. I learned to become a machine for efficiency — and for enjoying the work. I currently lead CE South HR operations at P&G.',
          photo: '/about-pg.jpg',
          photoAlt: 'Vedra Regul Erent-Ondrušek (P&G) with Diana Kobas Dešković (MODE1)',
        },
        {
          num: '02',
          title: 'Academic base',
          body: 'BA in sociology and German (2015). German studies are known for being gentle with students, which is where I developed iron discipline and lifelong imposter syndrome. When I started working in HR, the imposter syndrome demanded that I complete a postgraduate degree in HR Management (2021) at EFZG. The crown of that program: a paper on whether engaged onboarding is important for engaged work.',
          photo: '/s2-2-768x512.jpg',
          photoAlt: 'Academic study scene',
        },
        {
          num: '03',
          title: 'Executive Coaching',
          body: "I'm currently training for ICF-accredited Executive Coach certification. Coaching isn't a hobby for me — it's a serious discipline with clear standards and results. So far I've worked as a grief coach, a service I developed as part of my project Memoria.hr, writing and reading eulogies.",
          photo: '/about-coaching.jpg',
          photoAlt: 'Coaching session',
        },
        {
          num: '04',
          title: 'Phytotherapy and aromatherapy',
          body: 'Did you know standardized supplements contain far lower active-compound concentrations than a fresh, rich phytotherapy preparation? Wellbeing covers our physical, mental and emotional health — and I have used the power of herbal compounds for years for immunity, deep sleep, and staying calm in chaotic situations. In July 2026 I become a certified phyto-aromatherapist. I use this knowledge to build phyto-protocols for my coaching packages.',
          photo: '/about-phyto.jpg',
          photoAlt: 'Phytotherapy — plant preparations',
        },
        {
          num: '05',
          title: 'Body work: power posture and relaxation',
          body: 'I completed Fitness School (2013) and the Ana Maletić School of Contemporary Dance (2009) alongside high school. In my twenties I taught courses and workshops in Tribal Fusion bellydance, and I still dance today at Plesni centar Dhalia — which I co-founded. I use this knowledge to train power posture in clients and to release stress through body and movement.',
          photo: '/about-body.jpg',
          photoAlt: 'Body work — movement and posture',
        },
        {
          num: '06',
          title: 'School of life',
          body: "Maybe the most important one. I grew up in a family where my father was paralyzed when I was ten, alongside three younger brothers. I know first-hand how much it would have meant to us to have someone help organize our lives after that kind of change. Even so, I'm proud of how we carried it through — you can read about the hero Draško Regul here.",
          photo: '/vedra-1.jpg',
          photoAlt: 'Vedra Regul Erent-Ondrušek portrait',
        },
        {
          num: '07',
          title: 'Family',
          body: "I'm the mother of one charming small boy, Vilim, and wife to an even more charming lawyer, Filip — with whom I share the joy of corporate life. Both are frequent victims of my OPM, BCP and similar acronym implementations in our life together.",
          photo: null,
          photoAlt: 'Family photo — placeholder',
          missingPhoto: true,
        },
      ],
      labels: {
        prev: 'Previous',
        next: 'Next',
        progress: 'Slide',
        missingPhoto: 'MISSING PHOTO — Vedra to send',
      },
    },
    testimonials: {
      eyebrow: '06 / Proof',
      headline: 'No testimonials yet. On purpose.',
      body: "The 2026 founding cohort runs through the end of the year. Early clients shape how this practice gets built — and get my undivided attention while the calendar isn't full. You'll see testimonials here when I've earned them.",
    },
    principles: {
      eyebrow: '07 / Principles',
      headline: 'The operating manual.',
      sub: 'Six rules that run under every engagement. If you disagree with most of them, we are probably not a fit.',
      items: [
        {
          title: 'Authority precedes permission.',
          body: "You don't earn the right to lead by asking for it. You establish it, precisely, before anyone checks.",
          tag: 'Leadership',
        },
        {
          title: 'The body keeps your schedule.',
          body: 'If your nervous system says no, your calendar is lying. Fix the body, or the plan fails.',
          tag: 'Somatic',
        },
        {
          title: 'A career is a system, not a ladder.',
          body: 'Ladders have rungs. Systems have leverage points. Find yours.',
          tag: 'Career',
        },
        {
          title: 'Crisis runs on structure.',
          body: 'The only thing that works when nothing else does is cadence. Plan the next two weeks. Then the next two.',
          tag: 'Crisis',
        },
        {
          title: 'Generalists with discipline beat specialists without.',
          body: 'Four toolkits inside one operator outperform one toolkit inside a purist, every time.',
          tag: 'Practice',
        },
        {
          title: 'The loudest complaint is never the leak.',
          body: 'Symptoms are downstream. Diagnose where the energy actually goes, not where it gets noticed.',
          tag: 'Diagnostic',
        },
      ],
    },
    contact: {
      eyebrow: '08 / Contact',
      headline: "Let's write.",
      sub: 'The practice is new, the calendar is not full, and I read everything that lands in the inbox myself. Write a letter — short or long — and I reply personally, usually within 48 hours. Or book a call below.',
      paths: [
        {
          label: '01 / Fast',
          title: '15-minute audit.',
          body: 'Free diagnostic. Seven questions, three minutes, one written diagnosis. No pitch.',
          cta: 'Open the audit',
          href: '#note',
        },
        {
          label: '02 / Open',
          title: 'Write a letter.',
          body: 'Short or long. Specific or not. I read all of them.',
          cta: 'Email me',
          href: 'mailto:vedra.re.ondrusek@gmail.com',
        },
        {
          label: '03 / Book',
          title: 'Book a call.',
          body: 'Skip the form — pick a time on the calendar directly.',
          cta: 'Open the calendar',
          href: '#kontakt',
        },
      ],
      direct: {
        label: 'Or direct',
        email: 'vedra.re.ondrusek@gmail.com',
        phone: '+385 95 922 9547',
        location: 'Zagreb, Croatia',
      },
      note: {
        eyebrow: 'Or',
        headline: 'Send a note now.',
        sub: 'One field. No structure required.',
        placeholder: "What's on your mind?",
        submit: 'Send',
        sending: 'Sending…',
        sent: "Sent. I'll come back to you within two working days.",
        fromLabel: 'From',
        fromPlaceholder: 'name@domain.com',
      },
      calendar: {
        label: 'Prefer to skip the form?',
        linkLabel: 'Email me to book a 15-minute call →',
        href: 'mailto:vedra.re.ondrusek@gmail.com?subject=Booking%20a%2015-minute%20call',
        note: '',
      },
    },
    footer: {
      tagline: 'Practice of Vedra Regul Erent-Ondrušek',
      copyright: '© 2026 Trillian',
      legal: 'Zagreb, Croatia · OIB on request',
      blogLabel: 'Read the blog',
      blogHref: '/blog',
    },
    blog: {
      eyebrow: 'Blog · Notes from the practice',
      headline: 'Field notes on running life like an operation.',
      intro:
        'Short reads on corporate tools applied to private life, phyto-protocols, and what actually moves the needle on energy. Published when the thinking is done, not on a calendar.',
      empty: {
        title: 'The blog opens in weeks, not months.',
        body: "Below: the three pieces queued for the first drop. Leave your email and I'll send the first one directly.",
        cta: 'Back to site',
        ctaHref: '/',
      },
      upcomingLabel: 'First in the queue',
      upcomingPosts: [
        {
          num: '01',
          category: 'Authority',
          title: 'Why authority has to be set by day 14 — not argued for on day 90.',
          teaser:
            'The cost of waiting for permission, and four calibrated moves that establish who you are going to be in a new role before anyone else writes it for you.',
        },
        {
          num: '02',
          category: 'Phyto',
          title: 'Tinctures that actually sleep with you.',
          teaser:
            "Why shelf supplements are half-dose theater, what three Croatian plants outperform them at sleep and calm, and how an individualized preparation gets built.",
        },
        {
          num: '03',
          category: 'Systems',
          title: 'RACI the household. No, really.',
          teaser:
            "The one-page template that ended a year of low-grade domestic friction in our home. Plus the OPM move that comes next.",
        },
      ],
      subscribe: {
        eyebrow: 'Get the first one',
        headline: 'I send one email when the first post drops.',
        sub: 'No newsletter, no drip, no marketing. One note in your inbox when the first piece is up.',
        placeholder: 'you@domain.com',
        submit: 'Notify me',
        sending: 'Sending…',
        sent: "Noted — I'll reach out when the first post is up.",
        note: "Mailto-based for now; replies land in my inbox.",
      },
      labels: {
        back: 'Back',
        readMore: 'Read',
        published: 'Published',
      },
    },
    blogTeaser: {
      eyebrow: '\u2014 Blog',
      headline: 'Notes from the practice.',
      body: 'Short, infrequent reads. Corporate tools applied to private life, phyto-protocols, and the diagnostics behind each package.',
      previewLabel: 'Queued',
      cta: 'Open the blog',
    },
  },

  hr: {
    meta: {
      wordmark: 'Trillian',
      subtitle: 'coaching',
      location: 'Zagreb',
      practitioner: 'Vedra Regul Erent-Ondrušek',
    },
    nav: {
      home: 'Home',
      about: 'O meni',
      packages: 'Paketi',
      approach: 'Moj pristup',
      contact: 'Kontakt',
      blog: 'Blog',
      apply: "15′ Audit",
      services: 'Paketi',
      story: 'O meni',
      principles: 'Principi',
    },
    hero: {
      eyebrow: '01 / Bok',
      line1: 'Upravljaj svojim životom',
      line2Prefix: 'kao što upravljaš',
      line2Suffix: '.',
      rotating: ['biznisom', 'kompanijom', 'operacijom', 'timom'],
      sub: 'Implementiraj korporativne alate u svakodnevni život. Korporativna metodologija susreće biologiju performansi. Struktura i mjerljivi rezultati.',
      scroll: 'Skrolaj',
      dossier: ['Hrvatica', 'MSc HR · EFZG', 'P&G · Hitachi · dm', 'ICF · Fito / 07·2026'],
      portraitAlt: 'Vedra Regul Erent-Ondrušek — portret',
      ctaLabel: 'Javi se za 15′ AUDIT',
      ctaMicro: 'Besplatno · 7 pitanja · 3 minute',
    },
    manifesto: {
      eyebrow: '02 / Manifest',
      headline: 'Nisi tip za coaching?',
      lines: [
        'Moja metoda nije sjedenje na kauču i pričanje o problemima.',
        'Ovo je implementacija konkretnih alata — Organizational Performance Model, Kanban, RACI, Stakeholder mapping — u tvoj privatni život.',
        'Optimiziraj svoje najvažnije resurse: Vrijeme, Energiju, Fokus.',
        'Ne improviziraj gdje ne treba.',
        'Ako tvoj biznis ima KPI-je i jasne uloge, zašto tvoj privatni život nema?',
        'Instaliraj operativni sustav koji spaja korporativnu logiku i biološku regeneraciju.',
      ],
      emphasis: 'Instaliraj operativni sustav koji spaja korporativnu logiku i biološku regeneraciju.',
    },
    marquee: {
      words: [
        'RACI',
        'OPM',
        'Kanban',
        'Fitoterapija',
        'BCP',
        'Power posture',
        'Prvih 100 dana',
        'Dionici',
        '80/20',
        'Živčani sustav',
        'Somatsko',
        'Executive',
        'Oporavak',
        'Autoritet',
      ],
    },
    approach: {
      eyebrow: '03 / Moj pristup',
      headline: 'Četiri alata. Jedan operator.',
      pillars: [
        {
          label: '01',
          tag: 'Korporativni alati',
          title: 'Provjerene korporativne metode, primijenjene privatno.',
          body: 'Radimo analize procesa (kamo odlazi tvoje vrijeme?), RACI tablice (tko je u kući izvršitelj zadatka?), OPM (kako dalje nakon promjene?), 80/20 analize (što mi donosi najviše dobrobiti za najmanji ulog?) te mnoge druge po individualnoj potrebi. Cilj: maksimalna efikasnost uz minimalno rasipanje energije.',
        },
        {
          label: '02',
          tag: 'Coaching',
          title: 'Sadašnjost i budućnost, ne prošlost.',
          body: 'Coaching je fokusiran na sadašnjost i budućnost te postavlja snažna pitanja — kao coach podržavam te u otkrivanju vlastitih rješenja za životne odluke ili poslovne izazove. Savjetovanje mi dozvoljava da kažem svoje mišljenje o tome kako bi neki problem trebalo riješiti. Osobno pohađam i volim psihoterapiju, ali nisam licencirani psihoterapeut te ne mogu liječiti dijagnoze. Ovdje radimo coaching i savjetovanje.',
        },
        {
          label: '03',
          tag: 'Fitoterapija',
          title: 'Tinktura s tvojim imenom na bočici.',
          body: 'Hrvatska je bogata biljem koje obiluje aktivnim tvarima koje pozitivno djeluju na imunitet, nesanicu i opuštanje. Kao certificirana fitoaromaterapeutkinja educirala sam se o kemijskim spojevima tih biljaka te uživam u izradi snažnih i svježih fitoterapijskih biljnih pripravaka. Pripravci na tržištu (dodaci prehrani) nemaju snagu i koncentraciju aktivnih tvari kao svježe pripremljen i individualiziran pripravak. Napomena: ne izrađujem tinkture po narudžbi i ne prodajem pripravke za liječenje bolesti.',
        },
        {
          label: '04',
          tag: 'Rad s tijelom',
          title: 'Power posture i regulacija kroz tijelo.',
          body: '[AI draft — Vedra će finalizirati.] Tijelo pamti što kalendar traži. Petnaest godina u fitnesu i suvremenom plesu dalo mi je protokole za power posture — položaj tijela koji u sekundi šalje signal autoriteta — i za regulaciju kroz pokret: kratke sekvence disanja i mikropokreta koje otključavaju napetost u ramenima, vratu i dijafragmi. Ne trebaš sat joge prije važnog sastanka. Trebaš dvije minute precizne prakse kada tijelo dobije poruku da je sigurno.',
        },
      ],
      unifier: 'Četiri discipline, jedan operator. Trebaš sve četiri.',
    },
    gallery: {
      eyebrow: '04 / Bilješke s terena',
      headline: 'Gdje se posao događa.',
      caption: 'Praksa ima vrijeme, sate i prostoriju. Ovo su rubovi moje.',
      items: [
        {
          label: '01 / Jutro',
          title: 'Prije nego što se inbox otvori.',
          body: 'Bilježnica, čaj, tridesetak minuta koje nitko drugi ne posjeduje.',
          theme: 'ochre' as PlaceholderTheme,
          illustration: 'sunrise' as Illustration,
        },
        {
          label: '02 / Polje',
          title: 'Biljke koje rade popravak.',
          body: 'Fito protokoli kalibrirani na stvarni živčani sustav, ne na marketinška obećanja.',
          theme: 'moss' as PlaceholderTheme,
          illustration: 'botanical' as Illustration,
        },
        {
          label: '03 / Grad',
          title: 'Zagreb, 10000.',
          body: 'Gdje praksa živi. Internacionalni klijenti remote, lokalni u sobi.',
          theme: 'moss-ochre' as PlaceholderTheme,
          illustration: 'horizon' as Illustration,
        },
      ],
    },
    services: {
      eyebrow: '04 / Paketi',
      headline: 'Četiri programa za operatora.',
      hint: 'Klikni paket da otvoriš sesije. Cijena na upit.',
      items: [
        {
          outcome: 'Uđi u novu ulogu već s autoritetom.',
          body: 'Program za one koji se pripremaju za promaknuće ili su nedavno dobili višu poziciju. Autoritet postavljen do drugog tjedna, ne trećeg mjeseca.',
          scope: 'First 100 Days: Authority Accelerator',
          format: '1:1 · program',
          who: 'Viši operatori koji ulaze u ulogu s vidljivošću. Interne promocije gdje se letvica podigla. Vanjski angažmani u politički nepoznat teren.',
          beats: [
            { label: 'Sesija 01', text: 'Stakeholder Mapping' },
            { label: 'Sesija 02', text: 'First Wins strategija' },
            { label: 'Sesija 03', text: 'Somatic Leadership' },
            { label: 'Sesija 04', text: 'Fitoterapijski protokol (po potrebi)' },
            { label: 'Sesija 05', text: 'Tjedni 1:1 pregled' },
            { label: 'Sesija 06', text: '90-dnevna revizija' },
          ],
          deliverables: [
            'Napisan plan prvih 100 dana i mapa dionika',
            'Direktan telefonski pristup tijekom prvih 30 dana',
            'Somatski protokoli za trenutke pritiska',
          ],
          principle: 'Autoritet se postavlja do 14. dana. Ne argumentira se na 90.',
        },
        {
          outcome: 'Vodi domaćinstvo kao da zaslužuje strategiju.',
          body: 'Upravljaj kućanstvom preciznošću uspješne tvrtke. Manje trenja, više zajedničke energije, jasnije vlasništvo.',
          scope: 'Strategic Household Operations',
          format: '1:1 ili par · projektno',
          who: 'Parovi gdje jedna osoba nosi nevidljive operacije. Obitelji koje navigiraju bolest, selidbu ili školske tranzicije. Operatori koji su gradili tvrtke i pokušali snaći se doma na sreću.',
          beats: [
            { label: 'Sesija 01', text: 'Family RACI matrica' },
            { label: 'Sesija 02', text: 'Domestic Kanban' },
            { label: 'Sesija 03', text: 'Shared Vision Board' },
            { label: 'Sesija 04', text: 'Predložak tjednog ops sastanka' },
            { label: 'Sesija 05', text: 'Kvartalna revizija' },
            { label: 'Sesija 06', text: 'Somatski protokol za stres u kući' },
          ],
          deliverables: [
            'RACI dokument domaćinstva i predložak tjednih opsa',
            'Obiteljski BCP (Business Continuity Plan) predložak',
            'Prilagođene prakse oporavka za partnerstvo',
          ],
          principle: 'Dom bez strategije vodi onaj tko prvi pukne.',
        },
        {
          outcome: 'Utvrdi što ti razbija tjedan.',
          body: "Za profesionalce koji osjećaju da im 'curi' energija. Energetski P&L, kalendarska autopsija, postura i fito podrška — kalibrirano na stvarno curenje.",
          scope: 'High-Performance Audit',
          format: '1:1 · 15 min besplatna proba',
          who: 'Bilo tko visoko funkcionalan tko osjeća da sustav škripi. Prije izgaranja, dok još imaš izbor.',
          beats: [
            { label: 'Sesija 01', text: 'Energy Profit & Loss analiza' },
            { label: 'Sesija 02', text: 'Performance Gap Analysis' },
            { label: 'Sesija 03', text: 'Executive Posture & Authority' },
            { label: 'Sesija 04', text: 'Fitoterapijski protokol' },
            { label: 'Sesija 05', text: 'Kalendarska autopsija' },
            { label: 'Sesija 06', text: '30-dnevni follow-up' },
          ],
          deliverables: [
            'Pisani sažetak audita s jednom imenovanom polugom',
            'Individualni fito pripravak (zaliha za dva tjedna)',
            'Prije/poslije bazna linija energije',
          ],
          principle: 'Curenje nije tamo gdje je buka.',
        },
        {
          outcome: 'Nastavi funkcionirati kad život ne funkcionira.',
          body: 'Bolest. Gubitak. Razvod. Primjena korporativnog Business Continuity Planning-a (BCP) i Organization Performance Model-a (OPM) na privatni život u trenucima ekstremnog stresa.',
          scope: 'Crisis Support · Zaslužujem podršku',
          format: 'Po mjeri · krizni protokol',
          who: 'Ljudi usred krize koju nisu izabrali. Partneri, roditelji, operatori koji i dalje imaju ljude koji o njima ovise.',
          beats: [
            { label: 'Sesija 01', text: 'Business Continuity Plan (BCP)' },
            { label: 'Sesija 02', text: 'OPM za krizu' },
            { label: 'Sesija 03', text: 'Karta podrške i delegacija' },
            { label: 'Sesija 04', text: 'Tjedni 1:1' },
            { label: 'Sesija 05', text: 'Fitoterapijski protokol za iscrpljenost' },
            { label: 'Sesija 06', text: 'Direktan telefonski pristup' },
          ],
          deliverables: [
            'Pisani plan kontinuiteta i arhitektura podrške',
            'Prilagođena kadenca — bez limita sesija',
            'Direktan telefonski pristup za akutne trenutke',
          ],
          principle: 'Iz krize se ne razmišlja. Operira se kroz nju — dok se ozdravljuje.',
        },
      ],
      pricing: 'Cijena na upit. Vedra uskoro objavljuje tri fiksna paketa s jasnim brojem sesija.',
      labels: {
        who: 'Za koga je',
        beats: 'Sesije',
        deliverables: 'Još u paketu',
        principle: 'Princip',
        expand: 'Otvori',
        collapse: 'Zatvori',
      },
    },
    story: {
      eyebrow: '05 / O meni',
      headline: 'Ti i ja.',
      paragraphs: [
        'Nisam tipičan coach. Vjerojatno sam gora.',
        'Iza mene je 10 godina korporativne karijere, četiri u Procter & Gambleu — svjetskom zlatnom standardu za sustave i procese. Diplomirala sam sociologiju i njemački jezik, poslijediplomski Upravljanje ljudskim potencijalima na EFZG-u. Trenutačno sam u treningu za ICF akreditiranog Executive Coacha.',
        'Certificirani sam fitoaromaterapeut te koristim znanost o ekstraktima biljaka kako bih kreirala fito-protokole za biologiju i zdravlje. Plus: instruktorica fitnesa — koristim znanja o tijelu za power posture i upravljanje stresom.',
        'Što to znači za tebe? Nudim ti provjerene alate. Zašto sam gora? Jer očekujem rezultate.',
      ],
      credentials: 'ICF certifikacija · srpanj 2026. Certifikat iz fitoterapije · srpanj 2026.',
      portraitAlt: 'Vedra Regul Erent-Ondrušek',
      moreLabel: 'Više o meni',
    },
    about: {
      eyebrow: '05 / O meni',
      headline: 'Iskustvo i akademski put.',
      intro: 'Jednog dana, nakon iscrpljujućeg razdoblja života, moja psihoterapeutkinja mi je rekla da bih bila izvrstan coach za rad s ljudima. Nema većeg priznanja od žene koja poznaje moj najcrnji shadow self. No, evo i nekih opipljivih dokaza.',
      slides: [
        {
          num: '01',
          title: 'Korporativni Special Forces',
          body: 'Iza mene je 10 godina korporativne karijere, od čega su četiri u Procter & Gambleu, a ostale u Hitachiju, Transcomu i dm-drogeriemarktu. P&G je svjetski zlatni standard za sustave i procese. Tamo sam naučila postati stroj za efikasnost, ali i za uživanje u poslu. Trenutno u P&G-u vodim CE South HR operacije.',
          photo: '/about-pg.jpg',
          photoAlt: 'Vedra Regul Erent-Ondrušek (P&G) s Dianom Kobas Dešković (MODE1)',
        },
        {
          num: '02',
          title: 'Akademska baza',
          body: 'Diplomirala sam sociologiju i njemački jezik (2015). Germanisti su poznati po blagonaklonosti prema svojim studentima, tako da sam tu razvila čeličnu disciplinu i cjeloživotni imposter sindrom. Kada sam počela raditi u HR-u, imposter sindrom je zahtijevao da završim poslijediplomski studij Upravljanje ljudskim potencijalima (2021) na EFZG-u. Kruna tog studija: znanstveni rad o odnosu strukturiranog onboardinga i angažmana zaposlenika.',
          photo: '/s2-2-768x512.jpg',
          photoAlt: 'Akademski rad',
        },
        {
          num: '03',
          title: 'Executive Coaching',
          body: 'Trenutačno sam u treningu za ICF akreditiranog Executive Coacha. Coaching ne smatram hobijem, već ozbiljnom disciplinom s jasnim standardima i rezultatima. Do sada sam radila coaching u obliku grief coaching-a, usluge koju sam razvila u sklopu svog projekta Memoria.hr — pisanje i čitanje govora na sprovodima.',
          photo: '/about-coaching.jpg',
          photoAlt: 'Coaching sesija',
        },
        {
          num: '04',
          title: 'Fitoterapija i aromaterapija',
          body: 'Jesi znao da je u standardiziranim dodacima prehrani znatno manja količina djelatnih tvari nego u svježem fitoterapijskom pripravku? Wellbeing obuhvaća naše fizičko, mentalno i emocionalno zdravlje, a ja godinama koristim snagu biljnih droga za imunitet, izvrstan duboki san te da ostanem smirena u kaotičnim situacijama. U srpnju 2026. postajem certificirani fitoaromaterapeut. Znanja o kemijskim svojstvima biljaka koristim za izradu fito-protokola za svoje coaching pakete.',
          photo: '/about-phyto.jpg',
          photoAlt: 'Fitoterapija — biljni pripravci',
        },
        {
          num: '05',
          title: 'Rad s tijelom: Power Posture i relaksacija',
          body: 'Završila sam Fitnes učilište (2013) i Školu suvremenog plesa Ane Maletić (2009) uz gimnaziju. U dvadesetima sam vodila tečajeve i radionice Tribal Fusion trbušnog plesa, a plešem i danas u Plesnom centru Dhalia, čija sam suosnivačica. Ta znanja koristim za treniranje power posture položaja tijela kod klijenata te za opuštanje stresa kroz tijelo i pokret.',
          photo: '/about-body.jpg',
          photoAlt: 'Rad s tijelom — pokret i postura',
        },
        {
          num: '06',
          title: 'Životna škola',
          body: 'Možda i najvažnija. Odrasla sam u obitelji u kojoj je otac ostao nepokretan kad sam imala 10 godina, uz 3 mlađa brata. Iz prve ruke znam koliko bi nam značilo da smo tada imali nekoga tko bi nam organizirao život nakon takve promjene. No, i ovako sam ponosna na to kako smo svi to iznijeli, a o heroju Drašku Regulu može se pročitati više.',
          photo: '/vedra-1.jpg',
          photoAlt: 'Vedra Regul Erent-Ondrušek portret',
        },
        {
          num: '07',
          title: 'Obitelj',
          body: 'Majka sam jednog simpatičnog malog dječaka Vilima i supruga još simpatičnijeg pravnika Filipa s kojim dijelim sreću korporativnog svijeta. Obojica su česte žrtve mojih implementacija OPM-a, BCP-a i sličnih kratica u naš život.',
          photo: null,
          photoAlt: 'Obiteljska fotografija — placeholder',
          missingPhoto: true,
        },
      ],
      labels: {
        prev: 'Prethodno',
        next: 'Dalje',
        progress: 'Slide',
        missingPhoto: 'NEDOSTAJE FOTO — Vedra će poslati',
      },
    },
    testimonials: {
      eyebrow: '06 / Dokaz',
      headline: 'Bez svjedočanstava. Zasad. Namjerno.',
      body: 'Osnivačka generacija 2026. traje do kraja godine. Rani klijenti oblikuju kako ova praksa izgleda — i dobivaju moju nepodijeljenu pažnju dok kalendar nije pun. Svjedočanstva ćeš vidjeti kad ih zaslužim.',
    },
    principles: {
      eyebrow: '07 / Principi',
      headline: 'Operativni priručnik.',
      sub: 'Šest pravila koja idu ispod svakog angažmana. Ako se ne slažeš s većinom, vjerojatno nismo dobar par.',
      items: [
        {
          title: 'Autoritet prethodi dozvoli.',
          body: 'Pravo da vodiš ne zaslužuješ traženjem. Uspostavljaš ga, precizno, prije nego što itko provjeri.',
          tag: 'Vodstvo',
        },
        {
          title: 'Tijelo drži raspored.',
          body: 'Ako ti živčani sustav kaže ne, kalendar laže. Popravi tijelo, ili plan pada.',
          tag: 'Somatsko',
        },
        {
          title: 'Karijera je sustav, ne ljestve.',
          body: 'Ljestve imaju prečke. Sustavi imaju točke poluge. Pronađi svoje.',
          tag: 'Karijera',
        },
        {
          title: 'Kriza funkcionira na strukturi.',
          body: 'Jedino što radi kad ništa drugo ne radi je kadenca. Isplaniraj sljedeća dva tjedna. Pa sljedeća dva.',
          tag: 'Kriza',
        },
        {
          title: 'Generalisti s disciplinom pobjeđuju specijaliste bez.',
          body: 'Četiri alata u jednom operatoru nadmašuju jedan alat kod purista, svaki put.',
          tag: 'Praksa',
        },
        {
          title: 'Najglasnija žalba nikad nije curenje.',
          body: 'Simptomi su nizvodno. Dijagnosticiraj gdje energija stvarno odlazi, ne gdje se primjećuje.',
          tag: 'Dijagnoza',
        },
      ],
    },
    contact: {
      eyebrow: '08 / Kontakt',
      headline: 'Pišimo.',
      sub: 'Praksa je nova, kalendar nije pun, a sve što stigne u inbox sama čitam. Napiši pismo — kratko ili dugo — i javljam se osobno, obično unutar 48 sati. Ili zakaži poziv ispod.',
      paths: [
        {
          label: '01 / Brzo',
          title: 'Petnaestminutni audit.',
          body: 'Besplatna dijagnoza. Sedam pitanja, tri minute, jedna pisana dijagnoza. Bez prodaje.',
          cta: 'Otvori audit',
          href: '#note',
        },
        {
          label: '02 / Otvoreno',
          title: 'Napiši pismo.',
          body: 'Kratko ili dugo. Konkretno ili ne. Čitam sva.',
          cta: 'Pošalji email',
          href: 'mailto:vedra.re.ondrusek@gmail.com',
        },
        {
          label: '03 / Zakaži',
          title: 'Zakaži poziv.',
          body: 'Preskoči obrazac — odaberi termin direktno u kalendaru.',
          cta: 'Otvori kalendar',
          href: '#kontakt',
        },
      ],
      direct: {
        label: 'Ili direktno',
        email: 'vedra.re.ondrusek@gmail.com',
        phone: '+385 95 922 9547',
        location: 'Zagreb, Hrvatska',
      },
      note: {
        eyebrow: 'Ili',
        headline: 'Pošalji poruku sada.',
        sub: 'Jedno polje. Bez strukture.',
        placeholder: 'Što ti je na umu?',
        submit: 'Pošalji',
        sending: 'Šaljem…',
        sent: 'Poslano. Javim se u roku od dva radna dana.',
        fromLabel: 'Od',
        fromPlaceholder: 'ime@domena.com',
      },
      calendar: {
        label: 'Preskoči obrazac?',
        linkLabel: 'Pošalji email za 15-minutni poziv →',
        href: 'mailto:vedra.re.ondrusek@gmail.com?subject=Zaka%C5%BEujem%2015-minutni%20poziv',
        note: '',
      },
    },
    footer: {
      tagline: 'Praksa Vedre Regul Erent-Ondrušek',
      copyright: '© 2026 Trillian',
      legal: 'Zagreb, Hrvatska · OIB na upit',
      blogLabel: 'Pročitaj blog',
      blogHref: '/hr/blog',
    },
    blog: {
      eyebrow: 'Blog · Bilješke iz prakse',
      headline: 'Bilješke o vođenju života kao operacije.',
      intro:
        'Kratki tekstovi o primjeni korporativnih alata u privatnom životu, fito-protokolima i onome što stvarno pomiče iglu na energiji. Objavljuje se kad je tekst spreman, ne po kalendaru.',
      empty: {
        title: 'Blog se otvara u tjednima, ne mjesecima.',
        body: 'Ispod: tri teksta u redu za prvo objavljivanje. Ostavi email i javim se osobno kad prvi izađe.',
        cta: 'Natrag na stranicu',
        ctaHref: '/hr',
      },
      upcomingLabel: 'Prvi u redu',
      upcomingPosts: [
        {
          num: '01',
          category: 'Autoritet',
          title: 'Zašto autoritet treba postaviti do 14. dana — a ne argumentirati na 90.',
          teaser:
            'Koliko košta čekanje dozvole, i četiri kalibrirana poteza koji postavljaju tko ćeš biti u novoj ulozi prije nego što itko drugi napiše priču umjesto tebe.',
        },
        {
          num: '02',
          category: 'Fito',
          title: 'Tinkture koje stvarno spavaju s tobom.',
          teaser:
            'Zašto su dodaci prehrani na polici polovično kazalište, koje tri hrvatske biljke ih nadmašuju za san i smirenje, i kako se radi individualizirani pripravak.',
        },
        {
          num: '03',
          category: 'Sustavi',
          title: 'RACI za kućanstvo. Da, ozbiljno.',
          teaser:
            'Predložak na jednoj stranici koji je kod nas doma završio godinu tihog trenja. Plus OPM potez koji dolazi poslije.',
        },
      ],
      subscribe: {
        eyebrow: 'Javi kad izađe',
        headline: 'Pošalji jedan email kad prvi tekst izađe.',
        sub: 'Bez newslettera, bez dripa, bez marketinga. Jedna poruka u inbox kad prvi tekst bude gotov.',
        placeholder: 'ti@domena.com',
        submit: 'Prijavi me',
        sending: 'Šaljem…',
        sent: 'Zabilježeno — javim se kad prvi tekst izađe.',
        note: 'Za sada mailto — odgovori padaju direktno u moj inbox.',
      },
      labels: {
        back: 'Natrag',
        readMore: 'Čitaj',
        published: 'Objavljeno',
      },
    },
    blogTeaser: {
      eyebrow: '\u2014 Blog',
      headline: 'Bilješke iz prakse.',
      body: 'Kratki, rijetki tekstovi. Korporativni alati primijenjeni u privatni život, fito-protokoli i dijagnostika iza svakog paketa.',
      previewLabel: 'U redu',
      cta: 'Otvori blog',
    },
  },
} as const

export type Strings = typeof strings.en
